import type { Metadata } from "next"
import { Inter } from 'next/font/google'
import Script from "next/script"
import "./globals.css"
import { AuthProvider } from "@/contexts/auth-context"
import { NavigationGuardProvider } from "@/contexts/navigation-guard-context"
import { AppSidebar } from "@/components/app-sidebar-final" // Asegúrate de que esta importación sea correcta

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NavigationGuardProvider>
            <div className="flex h-screen">
              <AppSidebar />
              <main className="flex-1 overflow-y-auto">
                {children}
              </main>
            </div>
          </NavigationGuardProvider>
        </AuthProvider>
        {/* Script de Preline UI */}
        <Script src="/preline.js" strategy="afterInteractive" />
      </body>
    </html>
  )
}
