import { LayoutDashboard, Hotel, Building, Salad, Package, Utensils, FileText, DollarSign, Menu, BarChart, History, Scale, Settings, Users, Shield, Key, User, LogOut, ChevronDown, ChevronRight, Plus, ListChecks, FileUp, TrendingUp, PieChart, FileBarChart, Home, Lock, KeyRound, PillBottleIcon as PillBottle, Pill, ChevronUp } from 'lucide-react'

export const Icons = {
  LayoutDashboard,
  Hotel,
  Building,
  Salad,
  Package,
  Utensils,
  FileText,
  DollarSign,
  Menu,
  BarChart,
  History,
  Scale,
  Settings,
  Users,
  Shield,
  Key,
  User,
  LogOut,
  ChevronDown,
  ChevronRight,
  Plus,
  ListChecks,
  FileUp,
  TrendingUp,
  PieChart,
  FileBarChart,
  Home,
  Lock,
  KeyRound,
  PillBottle,
  Pill,
  ChevronUp,
}

export type Icon = keyof typeof Icons
